on:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    uses: ./.github/workflows/k8s-create-secret.yaml
    with:
      name: mysecret2
      includes: AB,CD,GH
    secrets: # Suggest using `secrets: inherit`
      CD: hello
      GH: there
