name: 'View the secrets context'
on:
  workflow_call:
    inputs:
      environment:
        required: true
  shell: bash
  run: echo "$SECRETS_CONTEXT"
  env:
    SECRETS_CONTEXT: ${{ toJson(secrets) }}