name: 'Get secrets'
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
jobs:
  get-secrets:
    name: 'Get secrets'
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: getsecrets
        run: |
          SECRETS_CONTEXT="${{ toJson(secrets) }}"
          input_json=$SECRETS_CONTEXT
          if [ -n "$input_json" ]; then
            create=("kubectl" "create" "secret" "generic" "database-vars")
            delete=("kubectl" "delete" "secret" "--ignore-not-found" "database-vars")
            while read -r key value; do
              create+=("--from-literal" "${key}=${value}")
            done < <(echo "$input_json" | jq -r 'to_entries[] | "\(.key) \(.value)"')
            "${delete[@]}"
            "${create[@]}"
          else
            echo "SECRETS_EXPORT environment variable not set"
          fi
        

  get-secrets:
    name: 'Get secrets'
    runs-on: ubuntu-latest
    needs: [configure]
    environment: staging/core-api
    steps:
      - name: getsecrets
        run: |
          SECRETS_CONTEXT="${{ toJson(secrets) }}"