on:
  workflow_call:
    inputs:
      runs-on:
        description: Platform to execute on
        type: string
        default: ubuntu-latest
        required: false
      aws-region:
        description: AWS region
        type: string
        default: eu-west-1
        required: false
      registry:
        description: AWS ECR registry
        type: string
        default: '887044485231.dkr.ecr.eu-west-1.amazonaws.com'
        required: false
      dockerfile:
        description: Path of dockerfile
        type: string
        default: 'Dockerfile'
        required: false
      build-args:
        description: Build arguments to pass to Docker build
        type: string
        required: false
      targets:
        description: Array of targets to build from the dockerfile
        type: string
        required: true
      tag-environment:
        description: Image tag containing the environment (e.g. production)
        type: string
        required: true
      tag-latest:
        description: Add the `latest` tag to the image
        type: boolean
        default: false
        required: false
    secrets:
      aws-access-key-id:
        description: AWS Access Key ID
        required: true
      aws-secret-access-key:
        description: AWS Secret Access Key
        required: true
    outputs:
      short-sha:
        description: Git commit short SHA
        value: ${{ jobs.build.outputs.short-sha }}
      unique-tag:
        description: Unique tag used for deployment
        value: ${{ jobs.build.outputs.unique-tag }}
jobs:
  build:
    runs-on: ${{ inputs.runs-on }}
    strategy:
      matrix:
        target: ${{ fromJson(inputs.targets) }}
      fail-fast: true
      max-parallel: 1
    outputs:
      short-sha: ${{ steps.git-meta.outputs.short-sha }}
      unique-tag: ${{ steps.git-meta.outputs.unique-tag }}
    steps:
      - name: 'Test matrix'
        run: echo "Running ${{ matrix.target }}"

      - name: 'Setup: Docker Buildx'
        # v2 (2.5.0) @ 10 Mar 2023 https://github.com/docker/setup-buildx-action/tags
        uses: docker/setup-buildx-action@4b4e9c3e2d4531116a6f8ba8e71fc6e2cb6e6c8c

      - name: 'Setup: Configure AWS credentials'
        # v2 (2.0.0) @ 7 Mar 2023 https://github.com/aws-actions/configure-aws-credentials/tags
        uses: aws-actions/configure-aws-credentials@e1e17a757e536f70e52b5a12b2e8d1d1c60e04ef
        with:
          aws-access-key-id: ${{ secrets.aws-access-key-id }}
          aws-secret-access-key: ${{ secrets.aws-secret-access-key }}
          aws-region: ${{ inputs.aws-region }}

      - name: 'Setup: Git checkout'
        # v3 (3.5.2) @ 02 Mar 2022 https://github.com/actions/checkout/tags
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab

      - name: 'Setup: Git meta'
        id: git-meta
        run: |
          echo "short-sha=`git rev-parse --short HEAD`" >> $GITHUB_OUTPUT
          echo "unique-tag=${{ inputs.tag-environment }}-`git rev-parse --short HEAD`" >> $GITHUB_OUTPUT

      - name: 'Setup: Login to ECR'
        # v1 (1.6.0) @ 30 Mar 2023 https://github.com/aws-actions/amazon-ecr-login/tags
        uses: aws-actions/amazon-ecr-login@2f9f10ea3fa2eed41ac443fee8bfbd059af2d0a4

      - name: 'Build and Push'
        # v4 (4.0.0) @ 30 Jan 2023 https://github.com/docker/build-push-action/tags
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ${{ inputs.dockerfile }}
          target: ${{ matrix.target }}
          build-args: ${{ inputs.build-args }}
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ${{ inputs.registry }}/${{ matrix.target }}:${{ inputs.tag-environment }}
            ${{ inputs.registry }}/${{ matrix.target }}:${{ github.run_number }}
            ${{ inputs.registry }}/${{ matrix.target }}:${{ steps.git-meta.outputs.short-sha }}
            ${{ inputs.registry }}/${{ matrix.target }}:${{ steps.git-meta.outputs.unique-tag }}

      - name: 'Set latest tag'
        if: ${{ inputs.tag-latest }}
        # v2 (2.1.0) @ 24 Nov 2022 https://github.com/akhilerm/tag-push-action/tags
        uses: akhilerm/tag-push-action@85bf542f43f5f2060ef76262a67ee3607cb6db37
        with:
          src: ${{ inputs.registry }}/${{ matrix.target }}:${{ steps.git-meta.outputs.unique-tag }}
          dst: ${{ inputs.registry }}/${{ matrix.target }}:latest
