on:
  workflow_call:
    inputs:
      runs-on:
        description: Platform to execute on
        type: string
        default: ubuntu-latest
        required: false
      aws-region:
        description: AWS region
        type: string
        default: us-east-1
        required: false
      registry:
        description: AWS ECR registry
        type: string
        default: '887044485231.dkr.ecr.us-east-1.amazonaws.com'
        required: false
      dockerfile:
        description: Path of dockerfile
        type: string
        default: 'Dockerfile'
        required: false
      build-args:
        description: Build arguments to pass to Docker build
        type: string
        required: false
      targets:
        description: Array of targets to build from the dockerfile
        type: string
        required: true
      tag-environment:
        description: Image tag containing the environment (e.g. production)
        type: string
        required: true
      tag-latest:
        description: Add the `latest` tag to the image
        type: boolean
        default: false
        required: false
    secrets:
      aws-access-key-id:
        description: AWS Access Key ID
        required: true
      aws-secret-access-key:
        description: AWS Secret Access Key
        required: true
    outputs:
      short-sha: 
        description: Git commit short SHA
        value: ${{ jobs.build.outputs.short-sha }}
      unique-tag:
        description: Unique tag used for deployment
        value: ${{ jobs.build.outputs.unique-tag }}
jobs:
  build:
    runs-on: ${{ inputs.runs-on }}
    strategy:
      matrix:
        target: ${{ fromJson(inputs.targets) }}
      fail-fast: true
      max-parallel: 1
    outputs:
      short-sha: ${{ steps.git-meta.outputs.short-sha }}
      unique-tag: ${{ steps.git-meta.outputs.unique-tag }}
    steps:
      - name: 'Test matrix'
        run: echo "Running ${{ matrix.target }}"

      - name: 'Setup: Docker Buildx'
        # v1 (1.6.0) @ 12 Nov 2021 https://github.com/docker/setup-buildx-action/tags
        uses: docker/setup-buildx-action@94ab11c41e45d028884a99163086648e898eed25

      - name: 'Setup: Configure AWS credentials'
        # v1 (1.6.1) @ 19 Jan 2022 https://github.com/aws-actions/configure-aws-credentials/tags
        uses: aws-actions/configure-aws-credentials@05b148adc31e091bafbaf404f745055d4d3bc9d2
        with:
          aws-access-key-id: ${{ secrets.aws-access-key-id }}
          aws-secret-access-key: ${{ secrets.aws-secret-access-key }}
          aws-region: ${{ inputs.aws-region }}

      - name: 'Setup: Git checkout'
        # v3 (3.0.0) @ 02 Mar 2022 https://github.com/actions/checkout/tags
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846

      - name: 'Setup: Git meta'
        id: git-meta
        run: |
          echo "::set-output name=short-sha::`git rev-parse --short HEAD`"
          echo "::set-output name=unique-tag::${{ inputs.tag-environment }}-`git rev-parse --short HEAD`"

      - name: 'Setup: Login to ECR'
        # v1 (1.3.3) @ 03 Nov 2021 https://github.com/aws-actions/amazon-ecr-login/tags
        uses: aws-actions/amazon-ecr-login@aaf69d68aa3fb14c1d5a6be9ac61fe15b48453a2

      - name: 'Build and Push'
        # v2 (2.10.0) @ 15 Mar 2022 https://github.com/docker/build-push-action/tags
        uses: docker/build-push-action@ac9327eae2b366085ac7f6a2d02df8aa8ead720a
        with:
          context: .
          file: ${{ inputs.dockerfile }}
          target: ${{ matrix.target }}
          build-args: ${{ inputs.build-args }}
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ${{ inputs.registry }}/${{ matrix.target }}:${{ inputs.tag-environment }}
            ${{ inputs.registry }}/${{ matrix.target }}:${{ github.run_number }}
            ${{ inputs.registry }}/${{ matrix.target }}:${{ steps.git-meta.outputs.short-sha }}
            ${{ inputs.registry }}/${{ matrix.target }}:${{ steps.git-meta.outputs.unique-tag }}

      - name: 'Set latest tag'
        if: ${{ inputs.tag-latest }}
        # v2 (2.0.0) @ 28 Sep 2021 https://github.com/akhilerm/tag-push-action/tags
        uses: akhilerm/tag-push-action@f973043dc002b8e5a772c53e79441e6e1861e874
        with:
          src: ${{ inputs.registry }}/${{ matrix.target }}:${{ steps.git-meta.outputs.unique-tag }}
          dst: ${{ inputs.registry }}/${{ matrix.target }}:latest
