on:
  workflow_call:
    inputs:
      runs-on:
        description: Platform to execute on
        type: string
        default: ubuntu-latest
        required: false
      tag: 
        description: Image tag to deploy
        type: string
        required: true
      namespace:
        description: Kubernetes namespace
        type: string
        required: true
      envmnt:
        required: true
        type: string
#    secrets:
#      kube-config:
#        description: KUBE_CONFIG file
#        required: true
#      aws-access-key-id:
#        description: AWS Access Key ID
#        required: false
#      aws-secret-access-key:
#        description: AWS Secret Access Key
#        required: false
jobs:
  build:
    runs-on: ${{ inputs.runs-on }}
    environment: ${{ inputs.envmnt }}
    steps:
      - name: 'Setup: Configure AWS credentials'
        # v1 (1.6.1) @ 19 Jan 2022 https://github.com/aws-actions/configure-aws-credentials/tags
        uses: aws-actions/configure-aws-credentials@05b148adc31e091bafbaf404f745055d4d3bc9d2
        with:
          aws-access-key-id: ${{ secrets.aws_access_key_id_eks }}
          aws-secret-access-key: ${{ secrets.aws_secret_access_key_eks }}
          aws-region: eu-west-1

      - name: 'Setup: Git checkout'
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846

      - name: getsecrets
        env: 
          input_json: ${{ toJson(secrets) }}
        run: |
          echo $input_json     
          if [ -n "$input_json" ]; then
            delete=("kubectl" "delete" "secret" "--ignore-not-found" "database-vars")
            create=("kubectl" "create" "secret" "generic" "database-vars")

            while IFS=: read -r key value; do
              trimmed_key=$(echo "$key" | tr -d '," ')
              trimmed_value=$(echo "$value" | tr -d '," ')
              create+=("--from-literal"="${trimmed_key}='${trimmed_value}'")
            done < <(echo "$input_json" | jq -r 'to_entries[] | "\(.key):\(.value)"')
            
            echo "${create[@]}"
          else
            echo "SECRET_CONTEXT environment variable not set"
          fi
#      - name: 'Deploy: Kubernetes apply'
#        run: |
#          kubectl delete -R -f build/${{ inputs.namespace }} --ignore-not-found=true -n${{ inputs.namespace }} --grace-period=10
#          kubectl apply -R -f build/${{ inputs.namespace }} -n${{ inputs.namespace }}



