on:
  workflow_call:
    inputs:
      runs-on:
        description: Platform to execute on
        type: string
        default: ubuntu-latest
        required: false
      tag: 
        description: Image tag to deploy
        type: string
        required: true
      namespace:
        description: Kubernetes namespace
        type: string
        required: true
      envmnt:
        required: true
        type: string

jobs:
  build:
    runs-on: ${{ inputs.runs-on }}
    environment: ${{ inputs.envmnt }}
    steps:
      - name: 'Setup: Git checkout'
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846

      - name: getsecrets
        run: |
          SECRETS_CONTEXT="${{ toJson(secrets) }}"
          echo "11"