on:
  workflow_call:
    inputs:
      namespace:
        description: Kubernetes namespace
        type: string
        required: true
      name:
        description: Kubernetes Secret name
        type: string
        required: true
      includes:
        description: List (comma-separated) of GitHub secret names to include in the Kubernetes Secret
        type: string
        required: true
    secrets:
      kube-config:
        description: KUBE_CONFIG file
        required: false
jobs:
  'create-secret':
    runs-on: ubuntu-latest
    steps:
      - name: 'Setup: Create yaml file'
        run: |
          cat <<EOF > secret.yaml
          apiVersion: v1
          kind: Secret
          metadata:
            name: ${{ inputs.name }}
            namespace: ${{ inputs.namespace }}
          type: Opaque
          stringData:
          EOF

      - name: 'Setup: Extract secrets and append to yaml'
        env:
          SECRETS_JSON: ${{ toJson(secrets) }}
        run: |
          keys=${{ inputs.includes }}
          for key in ${keys//,/ }
          do
              value=$(echo "$SECRETS_JSON" | jq -r ".$key")
              if [[ "$value" == "null" ]]; then
                  echo "$key not found in GitHub secrets. Abort!"
                  exit 1
              fi
              echo "Found: $key"
              echo "  $key: $value" >> secret.yaml
          done

      - name: 'Deploy: Kubernetes apply'
        if: ${{ secrets.kube-config }}
        # v1 (1.21.2) @ 03 Nov 2021 https://github.com/actions-hub/kubectl/tags
        uses: actions-hub/kubectl@365773786ebd92c7b36b6ab80e17d4a213ab0cd1
        env:
          KUBE_CONFIG: ${{ secrets.kube-config }}
        with:
          args: apply -f secret.yaml
