on:
  workflow_call:
    inputs:
      namespace:
        description: Kubernetes namespace
        type: string
        required: true
      name:
        description: Kubernetes Secret name
        type: string
        required: true
      includes:
        description: List (comma-separated) of GitHub secret names to include in the Kubernetes Secret
        type: string
        required: true
jobs:
  'create-secret':
    runs-on: ubuntu-latest
    steps:
      - name: 'Deploy'
        env:
          SECRETS_JSON: ${{ toJson(secrets) }}
        run: |
          keys=${{ inputs.includes }}
          args=()
          for key in ${keys//,/ }
          do
              value=$(echo "$SECRETS_JSON" | jq -r ".$key")
              if [[ "$value" == "null" ]]; then
                  echo "$key not found in GitHub secrets. Abort!"
                  exit 1
              fi
              args+=("--from-literal=\"$key=$value\"")
          done
          echo "Creating secret ${{ inputs.name }}..."
          kubectl create secret generic ${{ inputs.name }} ${arguments[@]} --save-config --dry-run=client -o yaml | kubectl apply -n ${{ inputs.namespace }} -f -
