name: 'Notify: Send'
on:
  workflow_call:
    inputs:
      branch-name:
        description: Branch name
        type: string
        required: true
      repo:
        description: Repository Name
        type: string
        required: true
      owner:
        description: Organization Name
        type: string
        required: false
        default: rfcx
      workflow-id:
        description: Workflow ID (e.g. build.yml)
        type: string
        required: true
      previous-run-id:
        description: Previous workflow run ID
        type: string
        required: true
      status:
        description: Current workflow status
        type: string
        required: true
      always:
        description: Always send notification
        type: boolean
        required: false
        default: false
      notification-title:
        description: Title in the notification
        type: string
        required: true
      notification-footer:
        description: Footer in the notification
        type: string
        required: false
      notification-success-statement:
        description: Positive statement for the success notification
        type: string
        required: false
        default: '{0} fixed the build!'
    secrets:
      slack-webhook:
        description: Slack Webhook URL
        required: true
      github-token:
        description: GitHub Token
        required: true
jobs:
  send:
    runs-on: ubuntu-20.04
    steps:
      - name: 'Setup: Git checkout'
        # v3 (3.5.2) @ 13 Apr 2023 https://github.com/actions/checkout/tags
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab

      # -------------------------------------------------- #
      # ALWAYS RUNS                                        #
      # -------------------------------------------------- #
      - name: 'Notify: Get conclusion of previous run'
        id: latest_run_conclusion
        # v2 (2.1.7) @ 11 Oct 2022 https://github.com/octokit/request-action/tags
        uses: octokit/request-action@89a1754fe82ca777b044ca8e79e9881a42f15a93
        if: inputs.previous-run-id
        with:
          # https://docs.github.com/en/rest/reference/actions#get-a-workflow-run
          route: GET /repos/{owner}/{repo}/actions/runs/{run_id}
          owner: ${{ inputs.owner }}
          repo: ${{ inputs.repo }}
          run_id: ${{ inputs.previous-run-id }}
        env:
          GITHUB_TOKEN: ${{ secrets.github-token }}

      - name: 'Notify: Log if no previous run conclusion'
        if: inputs.previous-run-id && steps.latest_run_conclusion.outputs.status != 200
        run: |
          echo "Previous run status: ${{ steps.latest_run_conclusion.outputs.status }}"

      - name: 'Notify: Get data of latest successful run'
        id: latest_success
        # v2 (2.1.7) @ 11 Oct 2022 https://github.com/octokit/request-action/tags
        uses: octokit/request-action@89a1754fe82ca777b044ca8e79e9881a42f15a93
        if: |
          !inputs.previous-run-id || fromJson(steps.latest_run_conclusion.outputs.data).conclusion != 'success'
        with:
          # https://docs.github.com/en/rest/reference/actions#list-workflow-runs
          route: GET /repos/{owner}/{repo}/actions/workflows/{workflow_id}/runs
          owner: ${{ inputs.owner }}
          repo: ${{ inputs.repo }}
          workflow_id: ${{ inputs.workflow-id }}
          per_page: 1
          branch: ${{ inputs.branch-name }}
          status: success
        env:
          GITHUB_TOKEN: ${{ secrets.github-token }}

      - name: 'Notify: Log date of latest successful run'
        if: steps.latest_success.outputs.status == 200
        run: |
          echo ${{ (fromJson(steps.latest_success.outputs.data).workflow_runs.length == 0 && 'No runs') || fromJson(steps.latest_success.outputs.data).workflow_runs[0].head_commit.timestamp }}

      - name: 'Notify: Get Slack User'
        # v0 (0.3.0) @ 23 Oct 2022 https://github.com/kanga333/variable-mapper/tags
        uses: kanga333/variable-mapper@3681b75f5c6c00162721168fb91ab74925eaebcb
        with:
          key: '${{ github.event.sender.login }}'
          map: |
            {
              "antonyharfield": { "SLACK_MENTION_USERS": "U09HZUDUY" },
              "rassokhin-s": { "SLACK_MENTION_USERS": "U0ADVPX35" },
              "Tooseriuz": { "SLACK_MENTION_USERS": "UC905TCTV" },
              "rassokhina-e": { "SLACK_MENTION_USERS": "U73MLD3UP" },
              "grindarius": { "SLACK_MENTION_USERS": "U014RN99J9Y" },
              "RatreeOchn": { "SLACK_MENTION_USERS": "UK4PVHM9C" },
              ".*": { "SLACK_MENTION_USERS": "" }
            }

      - name: 'Notify: Get Commit Title'
        id: git-meta
        run: |
          echo "commit-title=`git show -s --format='%s'`" >> $GITHUB_OUTPUT

      - name: 'Notify: Slack Failed'
        # v2 (2.3.0) @ 25 Oct 2022 https://github.com/ravsamhq/notify-slack-action/tags
        uses: ravsamhq/notify-slack-action@bca2d7f5660b833a27bda4f6b8bef389ebfefd25
        # Notify failure if previous run was not also a failure
        if: |
          inputs.always || !inputs.previous-run-id || steps.latest_run_conclusion.outputs.status != 200 || fromJson(steps.latest_run_conclusion.outputs.data).conclusion != 'failure'
        with:
          notify_when: 'failure,warning'
          status: ${{ inputs.status }}
          notification_title: '❌ ${{ inputs.notification-title }} <{repo_url}/tree/${{ inputs.branch-name }}|${{ inputs.branch-name }}>'
          message_format: '*FAILED* @ <{run_url}|${{ steps.git-meta.outputs.commit-title }}>'
          footer: ${{ inputs.notification-footer }}
          mention_users_when: 'failure,warnings'
          mention_users: ${{ env.SLACK_MENTION_USERS }}
        env:
          SLACK_WEBHOOK_URL: '${{ secrets.slack-webhook }}'

      - name: 'Notify: Slack Success'
        # v2 (2.3.0) @ 25 Oct 2022 https://github.com/ravsamhq/notify-slack-action/tags
        uses: ravsamhq/notify-slack-action@bca2d7f5660b833a27bda4f6b8bef389ebfefd25
        # Notify success if previous run was not also a success
        if: |
          inputs.always || !inputs.previous-run-id || steps.latest_run_conclusion.outputs.status != 200 || fromJson(steps.latest_run_conclusion.outputs.data).conclusion != 'success'
        with:
          notify_when: 'success'
          status: ${{ inputs.status }}
          notification_title: '✅ ${{ inputs.notification-title }} <{repo_url}/tree/${{ inputs.branch-name }}|${{ inputs.branch-name }}>'
          message_format: |
            *SUCCESS* @ <{run_url}|${{ steps.git-meta.outputs.commit-title }}> - ${{ format(inputs.notification-success-statement, github.event.head_commit.author.name) }} ${{ ((steps.latest_success.outputs.status != 200 || fromJson(steps.latest_success.outputs.data).workflow_runs.length == 0) && '(first run)') || format('(broken since {0})', fromJson(steps.latest_success.outputs.data).workflow_runs[0].head_commit.timestamp) }}
          footer: ${{ inputs.notification-footer }}
        env:
          SLACK_WEBHOOK_URL: '${{ secrets.slack-webhook }}'
