name: 'Notify: Prepare'
on:
  workflow_call:
    inputs:
      workflow-id:
        description: Workflow ID (e.g. build.yml)
        type: string
        required: true
      repo:
        description: Repository Name
        type: string
        required: true
      owner:
        description: Organization Name
        type: string
        required: false
        default: rfcx
    secrets:
      github-token:
        description: GitHub Token
        required: true
    outputs:
      branch-name:
        description: Branch Name
        value: ${{ jobs.prepare.outputs.branch-name }}
      previous-run-id:
        description: Previous Run ID
        value: ${{ jobs.prepare.outputs.previous-run-id }}
jobs:
  prepare:
    runs-on: ubuntu-20.04
    outputs:
      branch-name: ${{ steps.branch.outputs.branch-name }}
      previous-run-id: ${{ steps.previous-run.outputs.id }}
    steps:
      - name: 'Setup: Output branch name'
        id: branch
        run: |
          if [[ "${{ github.event_name }}" = "pull_request" ]]; then echo "branch-name=`echo ${GITHUB_HEAD_REF}`" >> $GITHUB_OUTPUT; else echo "branch-name=`echo ${GITHUB_REF#refs/heads/}`" >> $GITHUB_OUTPUT; fi

      - name: 'Setup: Get ID of previous run' # Need to execute this early (before another run starts)
        id: workflow-runs
        uses: octokit/request-action@v2.1.7
        # v2 (2.1.7) @ 11 Oct 2022 https://github.com/octokit/request-action/tags
        with:
          # https://docs.github.com/en/rest/reference/actions#list-workflow-runs
          route: GET /repos/{owner}/{repo}/actions/workflows/{workflow_id}/runs
          owner: ${{ inputs.owner }}
          repo: ${{ inputs.repo }}
          workflow_id: ${{ inputs.workflow-id }}
          per_page: 2
          branch: ${{ steps.branch.outputs.branch-name }}
        env:
          GITHUB_TOKEN: ${{ secrets.github-token }}

      - name: 'Setup: Output run ID'
        id: previous-run
        run: |
          echo "id=${{ fromJson(steps.workflow-runs.outputs.data).workflow_runs[1].id }}" >> $GITHUB_OUTPUT
